// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pwrfcakpgayouydvisaz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3cmZjYWtwZ2F5b3V5ZHZpc2F6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMzQ4MzQsImV4cCI6MjA2MzYxMDgzNH0.9tDrb9kap14o5rWU90ESdtU9_bHAgWzz4Qmmm9HW5_Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);